### 登陆
POST {{host}}/api/login
Content-Type: application/x-www-form-urlencoded

account={{account}}&password={{password}}

> {% client.global.set("Set-Cookie", response.headers.valueOf("Set-Cookie")) %}

### 测试接口
GET {{host}}/api/security/test
Accept: application/json
Cookie: {{Set-Cookie}}

###